### ISSUE TITLE
Changing the language does not work anymore with Ember.js 1.13

### ISSUE THREAD

**Issue by hinti** [OCTRI/ember-i18next#16]
Using Ember.js 1.12 setting the property
```
this.set('i18n.locale', 'fr');
```
changed the language the app is displayed in.

Beginning with version 1.13 this doesn't work anymore.

**Comment by heathharrelson** [comment]
Thanks for testing this with Ember 1.13. I expect to work on getting our app on Ember. 1.13 next week, and will address this at that time.

**Comment by hinti** [comment]
@heathharrelson Thank you!

**Comment by heathharrelson** [comment]
@hinti If you get a chance, please test your app with version 1.0.0-beta.1 and let me know if it works for you.

**Comment by hinti** [comment]
@heathharrelson Works for me! Thx
