### ISSUE TITLE
Provide Ember 2.2.0 Initializer example

### ISSUE THREAD

**Issue by MyrdhinBZH** [OCTRI/ember-i18next#23]
Thank you for all your work!

I would like to use Initializers in my Ember 2.2 Application to load a default language and inject 'i18n' in routes and controllers. Could you provide an example? Thank you

**Comment by heathharrelson** [comment]
I'm open to documenting additional ways to initialize the library, but could you give me a little more information on what you're trying to do? For instance, why doesn't setting the default language via the `environment.js` work for you? And why not use `Ember.inject.service()` or the `I18nMixin` to inject the service?

**Comment by heathharrelson** [comment]
I'm going to close this issue due to the lack of response. If you can provide additional details about the problem you're trying to solve, you can open a new issue.
