### ISSUE TITLE
Rejected Promise in Init With Missing Locale Files

### ISSUE THREAD

**Issue by heathharrelson** [OCTRI/ember-i18next#30]
With i18next 1.10.X and 1.11.X, `initLibraryAsync` will log a warning about rejected promises if any locale files are missing. For instance, if the app provides an en-US locale file, but no generic en locale file, en.json will cause a 404, triggering the warning. This does not happen with i18next 1.9 and earlier.

Look into the impact of the rejected promise and what can be done to prevent it.

Could be obsoleted by #27, which will convert the addon to use i18next 2.X.

**Comment by heathharrelson** [comment]
Still present in ember-i18next 2.0.0 betas using i18next 3.x, but it doesn't appear to affect initialization.

**Comment by mpirio** [comment]
Hello,

The possibility of raising the error again could be useful in the case where we would like to manage a custom behavior (like a redirection to an error page if locale files are missing).

To have no impact on the existing code, we could offer an option activating this new error raising.

**Comment by heathharrelson** [comment]
@mpirio, that's a good idea. What sort of API do you imagine for this? Registering a callback to handle missing locale files, perhaps?

**Comment by heathharrelson** [comment]
Looking at the code, I think it will be straightforward to replace the `console.warn` in the `catc` block with a configurable rejection handler of some sort, similar to the pre/post-init actions.

https://github.com/OCTRI/ember-i18next/blob/332586b44841aee16afd18a02aa7596347e9aa19/addon/services/i18n.js#L62-L76

**Comment by mpirio** [comment]
Hello,

In this code, we lost "reason" if the user want to catch when he use "initLibraryAsync()". I propose another code (in "initLibraryAsync" and "_initLibrary") :

```javascript
  initLibraryAsync() {
    const i18next = this.get('i18next');
    const options = config.i18nextOptions || {};

    return this._runPreInitActions()
      .then(() => this._initLibrary())
      .then(() => this._runPostInitActions())
      .then(() => {
        this.set('_locale', i18next.language);
        this.set('isInitialized', true);
        return resolve();
      }).catch(reason => {
        // eslint-disable-next-line no-console
        console.warn(`A promise in the i18next init chain rejected with reason: ${reason}`);
        if (options.rejectError) {
          return reject(reason);
        }
      });
  },

...



_initLibrary() {
    const i18next = this.get('i18next');
    const options = config.i18nextOptions || {};

    let errors;

    //
    //  TODO:  Adding i18nextXHRBackend by default so that translation
    //         files can be loaded.
    //         How do we extend this so that other plugins can be added
    //         dynamically?
    //
    return i18next
      .use(i18nextXHRBackend)
      .init(options, (err) => {
        if (err) errors = err;
      })
      .then(() => {
        if (errors) {
          return reject(errors);
        }
        else {
          return resolve(i18next);
        }
      });
  },
```

If user configure with `rejectError = true` in config, he could use this in its application route :

```javascript
beforeModel() {
    return this.get('i18n')
        .initLibraryAsync()
        .catch(
            errors => this.transitionTo('my-error-Page', errors)
        );
}
```

I can PR this code :)

**Comment by heathharrelson** [comment]
Thanks for the detailed example. A PR would definitely be welcome.

**Comment by heathharrelson** [comment]
This can now be handled using the `rejectErrors` feature added in #95.
